require 'vagrant-aws'
require 'yaml'

cred = YAML.load_file(ENV['HOME'] + '/.ssh/api_cred.yml')# Create and configure the AWS instance(s)

Vagrant.configure("2") do |config|
    config.vm.box = "dummy"
    config.vm.provision :shell, path: "bootstrap.sh"

    config.vm.provider :virtualbox do |vb, override|
      override.vm.box = 'ubuntu/xenial64'
      override.vm.network "private_network", ip: "22.22.22.22"
      #local.vm.synced_folder "/vagrant"
    end

    config.vm.provider 'aws' do |aws, override|
      aws.access_key_id = cred['aws']['aws_access_key_id']
      aws.secret_access_key = cred['aws']['aws_secret_access_key']
      aws.keypair_name ='gu5sfdejcadmin'
      aws.instance_type = 't2.micro'
      aws.region = 'us-east-1'
      aws.ami = 'ami-f4cc1de2'
      aws.security_groups = ['launch-wizard-1']
      override.ssh.username = 'ubuntu'
      override.ssh.private_key_path = '~/.ssh/gu5sfdejcadmin.pem'
    end
end
